### ISSUE TITLE
Rendering on PyPI broken since 1.2.0

### ISSUE THREAD

**Issue by sbhtw** [sloria/flask-konch#4]
See https://pypi.python.org/pypi/flask-konch

Previous version was fine, see Google cache:
https://webcache.googleusercontent.com/search?q=cache:u4h4h81Yl0MJ:https://pypi.python.org/pypi/flask-konch

(as long as 1.2.0 is not indexed)

**Comment by sbhtw** [comment]
Another side note: the image at the top of `README.rst` is a 404:

    .. image:: https://dl.dropboxusercontent.com/u/1693233/github/flask-konch.png
        :alt: Flask-Konch

**Comment by sloria** [comment]
I'll look into this after work today.

Re: the image--Dropbox changed the way they do public files, which broke that image. I'll fix that, too later.
